### ISSUE TITLE
ModuleNotFoundError: No module named 'binary_utils'

### ISSUE THREAD

**Issue by palomo11** [oschakoory/RiboTaxa#2]
Hi, I am trying to use RiboTaxa but I'm encountering this error:

```
  File "/data/ese-alexp/software/RiboTaxa//scripts/matam_db_preprocessing.py", line 10, in <module>
    from binary_utils import Binary
ModuleNotFoundError: No module named 'binary_utils'
```

when trying to index the database:

bash -i /mypath/RiboTaxa/indexDB_RiboTaxa.sh /mypath/RiboTaxa/indexDB_arguments.conf

I followed the installation, and I have tried running indexDB_RiboTaxa.sh with:
conda activate RiboTaxa_py36, conda activate RiboTaxa_py27 and without activating conda, and always same issue.

Any idea about whats is going on?

**Comment by oschakoory** [comment]
Hi,
Thank you for using RiboTaxa!

I have fixed the missing module using conda.

Can you redo these steps:

```bash
git clone https://github.com/oschakoory/RiboTaxa.git
cd RiboTaxa
bash conda_virt_env.sh
```
The missing module will be installed in RiboTaxa and you will be able to index your database without error.

**Comment by palomo11** [comment]
That solved the issue. Thanks!
