### ISSUE TITLE
Version of scikit-learn

### ISSUE THREAD

**Issue by jeffe107** [oschakoory/RiboTaxa#5]
Hi,

Thank you for such great pipeline. I installed it, although while running it, there was a problem with the scikit-learn classifying step: 

`The scikit-learn version (0.23.1) used to generate this artifact does not match the current version of scikit-learn installed (0.24.1). Please retrain your classifier for your current deployment to prevent data-corruption errors.`

I tried to downgrade the scikit-learn through mamba (conda is extremely slow), and I obtained this error:

`package q2-diversity-2022.11.1-py38_0 requires scikit-learn 0.24.1.*, but none of the providers can be installed.`

Do you have any idea about how to solve this inconvenient?

**Comment by oschakoory** [comment]
Hi,
please verify the version of qiime2 database. It should be qiime2022.11.

Else you can also download it directly from here:

https://ucafr-my.sharepoint.com/personal/oshma_chakoory_uca_fr/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Foshma%5Fchakoory%5Fuca%5Ffr%2FDocuments%2FDatabases&ga=1

Do not hesitate if you have any question.

Oshma Chakoory
